version: '3.4'

services:
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Services/IdentityServer/Dockerfile

  tododb:
    image: mongo

  #identitydb:
  #  image: mcr.microsoft.com/mssql/server

  todo.api:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: Services/Todo/Todo.API/Dockerfile

volumes:
  mongo_data:
